### ISSUE TITLE
Return a markdown parsed by the gatsby-transformer-remark

### ISSUE THREAD

**Issue by ThiagoMiranda** [mpartipilo/gatsby-source-cockpit#3]
Hi..
I was wondering if I can get a "parsed" markdown from the GraphQL so I've posted an issue on Gatsby repo. So one of the contributos answered me this:
https://github.com/gatsbyjs/gatsby/issues/4987#issuecomment-381429902

But I can't get the markdown ( just a string with it unparsed ). Can you help me? Thanks

**Comment by mpartipilo** [comment]
Hi Thiago!

I see on that other issue that you managed to find the right child node. I
am currently in the process of documenting and redesigning a few parts of
the plugin.

When I wrote it I was new to both gatsby and cockpit, and made some
compromises.

Please let me know if there's anything else I can help you with any further.

**Comment by mpartipilo** [comment]
Hi Thiago!

I see on that other issue that you managed to find the right child node. I
am currently in the process of documenting and redesigning a few parts of
the plugin.

Just in case, for anyone tuning in:

Your collection called `Blog` will be available through `allCockpitBlog`. The nodes here will get a `childCockpitBlogContentTextNode` with a properly transformed `childMarkdownRemark` node.

```
query {
  allCockpitBlog {
    edges {
      node {
        childCockpitBlogContentTextNode {
          childMarkdownRemark {
            html
          }
        }
      }
    }
  }
}
```

When I wrote it I was new to both gatsby and cockpit, and made some
compromises. This will definitely change and become more readable.

Please let me know if there's anything else I can help you with any further.

**Comment by ThiagoMiranda** [comment]
I´ve found it. Thanks @mpartipilo 
Another thing: How do you handle images ( and other assets )? I was able to upload it to Cockpit but all the path is relative to the cockpit´s folder so it won´t load on the gatsby site. Do you have some treatment like the [gatsby-plugin-cockpit](https://www.npmjs.com/package/gatsby-plugin-cockpit) ? 
I was wondering if I can delegate the images to the `gatbsy-remark-images`

**Comment by mpartipilo** [comment]
It's in the plan.

Right now I handle images in a very strange way and remark won't pick then
up. I have to finish something elsw first before I work on the plugin.
It'll be a couple days.

**Comment by mpartipilo** [comment]
I do get the assets and the urls for the images are pointing to the cockpit
instance. That was always my intention. I only pick the image and gallery
field types and attach an asset if found.

**Comment by ThiagoMiranda** [comment]
I'm looking forward it.
Thanks for the plugin!

**Comment by kekami** [comment]
@mpartipilo 
Hello, thanks for the plugin. Just wondering if there is a status update on the image fix ?

**Comment by mpartipilo** [comment]
I will update the plugin soon with many fixes and features. Sorry it has taken so long.

**Comment by kekami** [comment]
Great to hear! Looking forward to it. Have you thought about making it possible to use gatsby-image plugin in the graphql queries?

**Comment by mpartipilo** [comment]
Sure! In summary I will add support for assets as files, image-sharp, languages, migrate to ginetta/cockpit-sdk, Gatsby dev real-time updates, images in markdown and wysiwyg, more field types, etc.
