### ISSUE TITLE
gatsby build fails

### ISSUE THREAD

**Issue by Craeckerffm** [mpartipilo/gatsby-source-cockpit#6]
**gatsby**: 2.0.17
**gatsby-plugin-cockpit:** 1.0.39

**Error Message:**

Your plugins must export known APIs from their gatsby-node.js.
The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs

- The plugin "gatsby-plugin-cockpit@1.0.39" is exporting a variable named "collectionsItems" which isn't an API.

- The plugin "gatsby-plugin-cockpit@1.0.39" is exporting a variable named "regionsItems" which isn't an API.

- The plugin "gatsby-plugin-cockpit@1.0.39" is exporting a variable named "collectionsNames" which isn't an API.

**Comment by mpartipilo** [comment]
That’s a different plugin, not the one I develop.

I can try mine out later with gatsby v2 and see if there’s any work to be
done.

**Comment by Craeckerffm** [comment]
cheeese, im sorry.
i got fooled by the github link on the gatsby plugin-page
